export const FETCH_HOMEPAGE = 'FETCH_HOMEPAGE';
export const FETCH_SINGLE_NEWS = 'FETCH_SINGLE_NEWS';
export const FETCH_SIDEBAR_DATA = 'FETCH_SIDEBAR_DATA';
export const FETCH_SINGLE_CATEGORY_DATA = 'FETCH_SINGLE_CATEGORY_DATA';
export const FETCH_SINGLE_TAG_DATA = 'FETCH_SINGLE_TAG_DATA';
export const FETCH_NEWS_COMMENT = 'FETCH_NEWS_COMMENT';
